name: "Setup EnhanceDocs"
description: 'Setup EnhanceDocs CLI in your Github Actions workflow.'
author: EnhanceDocs

inputs:
  api-key:
    description: 'Your EnhanceDocs Secret API Key.'
    required: true
  cli-version:
    description: 'EnhanceDocs CLI version. A value of `latest` will install the latest version of EnhanceDocs CLI. Defaults to `latest`.'
    default: "latest"
    required: false

runs:
  using: "composite"
  steps:
    - run: pip install enhancedocs==${{ inputs.cli-version }}
      shell: bash
    - run: echo "ENHANCEDOCS_API_KEY=${{ inputs.api-key }}" >> $GITHUB_ENV
      shell: bash

branding:
  icon: 'book'
  color: 'blue'
